Repository creatis-myriad/ASCENT, pull requests merged in 2023-03, with the labels that each got.

#73 Created abstract classes for `train`/`evaluate`/`predict` + Forced tags interpolation when printing
  ascent/eval.py
  ascent/predict.py
  ascent/train.py
  ascent/utils/rich_utils.py
Labels: enhancement

#74 Fix docstring and f-string printing
  ascent/datamodules/nnunet_datamodule.py
  ascent/datamodules/nnunet_dealias_datamodule.py
  ascent/preprocessing/experiment_planner_2DUNet.py
  ascent/preprocessing/experiment_planner_3DUNet.py
Labels: enhancement

#76 Update __init__.py
  ascent/__init__.py
Labels: bug

#78 Added flag to apply `softmax` in the `predict` function + Fixed typo
  ascent/models/nnunet_module.py
Labels: bug, enhancement

#79 Fixed type errors and Set `apply_softmax` to False during prediction in `nnunet_reg_module`
  ascent/models/nnunet_module.py
  ascent/models/nnunet_reg_module.py
Labels: bug

#80 Fixed bug where `apply_softmax` was not used in `tta_predict`
  ascent/models/nnunet_module.py
Labels: bug

#81 Fixed bug in `tta_predict`
  ascent/models/nnunet_module.py
Labels: bug

#82 Fixed `mirrors-prettier` version
  pyproject.toml
Labels: bug

#83 Removed `mirrors-prettier` that caused `poetry install` to fail
  pyproject.toml
Labels: bug

#92 Update dependabot.yml
  .github/dependabot.yml
Labels: bug

#93 Update dependabot.yml
  .github/dependabot.yml
Labels: bug, dependencies

#94 Ignore `dev` packages in dependabot
  .github/dependabot.yml
Labels: enhancement, dependencies

#95 Corrected bug in planner and Updated README
  README.md
  ascent/preprocessing/experiment_planner_2DUNet.py
Labels: bug

#97 Modify Comet model logging to always log both best and last models
  ascent/train.py
Labels: enhancement

#98 Added `auto_cast_data` decorator
  ascent/utils/decorators.py
Labels: enhancement

#96 Add support for `submitit` Hydra launcher
  .env.example
  ascent/__init__.py
  ascent/configs/eval.yaml
  ascent/configs/hydra/launcher/alliancecan.yaml
  ascent/configs/hydra/launcher/beluga.yaml
  ascent/configs/launcher/alliancecan.yaml
  ascent/configs/launcher/beluga.yaml
  ascent/configs/train.yaml
  pyproject.toml
Labels: enhancement, dependencies

#100 Updated `auto_cast_data` decorator to cast all Tensor args and kwargs
  ascent/utils/decorators.py
  ascent/utils/format/torch.py
Labels: enhancement

#101 Fixed bugs related to wrong `_self_` position in train/val.yaml
  ascent/configs/eval.yaml
  ascent/configs/train.yaml
Labels: bug
